<template>
  <div class="standards-page">
    <header><p class="eyebrow">Our standards</p><h1>A smaller catalogue needs a stronger point of view.</h1><p>BundleBee is an editorial discovery service for distinctive gifts. Inclusion is a judgement, not something a commission rate can buy.</p></header>
    <section class="standards-grid">
      <article><span>We look for</span><h2>A reason to remember it</h2><p>Thoughtful design, skilled making, a compelling idea, personal meaning or a genuinely useful improvement on the ordinary.</p></article>
      <article><span>We write</span><h2>Original, factual introductions</h2><p>We avoid copied product descriptions and unsupported claims. Where a quality matters, it should be specific and verifiable.</p></article>
      <article><span>We select</span><h2>Fewer, clearer routes</h2><p>A partner page should communicate a world and help a person choose. It should not reproduce the retailer’s complete catalogue.</p></article>
      <article><span>We publish</span><h2>Only after approval</h2><p>Partner products remain drafts until the programme is joined, imagery is authorised and working tracked links have been checked.</p></article>
    </section>
    <section class="disclosure" id="affiliate-disclosure"><div><p class="eyebrow">Affiliate disclosure</p><h2>How BundleBee is funded</h2></div><div><p>Some links on BundleBee are affiliate links. If a customer follows one and makes a qualifying purchase, BundleBee may receive a commission from the retailer at no extra cost to the customer.</p><p>Affiliate availability does not guarantee inclusion or determine our editorial opinion. We do not hide redirects, place cookies without a genuine click, bid on partner brand terms, or publish unofficial voucher codes.</p></div></section>
    <section class="previews"><p class="eyebrow">Private concepts</p><h2>What an advertiser receives before publication</h2><p>An applied partner may receive an unlisted concept page that demonstrates our intended presentation. These pages are excluded from navigation and search indexing, contain no live purchase link, and use no partner imagery until permission is in place.</p><router-link to="/for-partners">See the generic partner example</router-link></section>
  </div>
</template>

<style scoped>
.standards-page{display:grid;gap:4rem;padding:clamp(1rem,5vw,4rem) 1rem 5rem}.standards-page>header{max-width:880px}.eyebrow{margin:0;color:var(--bb-primary-dark);font-size:.76rem;font-weight:900;letter-spacing:.11em;text-transform:uppercase}h1{margin:.45rem 0 1rem;font-size:clamp(2.7rem,7vw,5.7rem);line-height:.96;letter-spacing:-.055em}.standards-page>header>p,.standards-grid p,.disclosure p,.previews p{color:var(--bb-muted);line-height:1.7;font-size:1.02rem}.standards-grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--bb-border);border-radius:24px;overflow:hidden}.standards-grid article{padding:clamp(1.3rem,3vw,2.3rem);border-bottom:1px solid var(--bb-border)}.standards-grid article:nth-child(odd){border-right:1px solid var(--bb-border)}.standards-grid article:nth-last-child(-n+2){border-bottom:0}.standards-grid span{color:var(--bb-primary-dark);font-weight:900;text-transform:uppercase;font-size:.75rem;letter-spacing:.08em}.standards-grid h2{margin:.5rem 0;font-size:1.65rem}.disclosure{display:grid;grid-template-columns:.8fr 1.2fr;gap:2rem;padding:clamp(1.4rem,4vw,3rem);border-radius:24px;background:color-mix(in srgb,var(--bb-accent) 18%,var(--bb-surface));border:1px solid color-mix(in srgb,var(--bb-accent) 55%,var(--bb-border))}.disclosure h2,.previews h2{margin:.4rem 0;font-size:clamp(2rem,4vw,3.3rem);line-height:1.05}.disclosure p:first-child{margin-top:0}.previews{max-width:760px}.previews a{display:inline-flex;margin-top:.5rem;color:var(--bb-primary-dark);font-weight:800}
@media(max-width:700px){.standards-page{padding:.5rem 0 3rem;gap:2.8rem}h1{font-size:2.8rem}.standards-grid,.disclosure{grid-template-columns:1fr}.standards-grid article,.standards-grid article:nth-child(odd),.standards-grid article:nth-last-child(-n+2){border-right:0;border-bottom:1px solid var(--bb-border)}.standards-grid article:last-child{border-bottom:0}.disclosure{gap:.5rem;padding:1.2rem}}
</style>

